# Generated by Django 6.0.1 on 2026-01-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='event_date',
            new_name='event_end_date',
        ),
        migrations.AddField(
            model_name='lead',
            name='event_end_session',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='Evening', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='event_start_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='event_start_session',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='Morning', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
