# Generated by Django 6.0.1 on 2026-02-02 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_event_date_lead_event_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TO_ASSIGN', 'To Be Assigned'), ('PRE_PRODUCTION', 'Pre Production'), ('SELECTION', 'Selection'), ('POST_PRODUCTION', 'Post Production'), ('COMPLETED', 'Completed')], default='TO_ASSIGN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.lead')),
            ],
        ),
    ]
