# Generated by Django 6.0.1 on 2026-02-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teammember_projecttask_projectteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='phase',
            field=models.CharField(choices=[('PLANNING', 'Planning & Coordination'), ('HARD_DISK', 'Hard Disk Collection'), ('PRE_WEDDING', 'Pre Wedding Shoot'), ('MAIN', 'Main Coverage Phase')], default='PLANNING', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttask',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
