# Generated by Django 6.0.1 on 2026-02-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projecttask_description_projecttask_phase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
