# Generated by Django 6.0.1 on 2026-02-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_projecttask_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
