# Generated by Django 6.0.1 on 2026-02-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_projecttask_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
