# Generated by Django 6.0.1 on 2026-02-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_projecttask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='phase',
            field=models.CharField(choices=[('PLANNING', 'Planning & Coordination'), ('HARD_DISK', 'Hard Disk Collection'), ('PRE_WEDDING', 'Pre Wedding Shoot'), ('MAIN', 'Main Coverage Phase'), ('SELECTION', 'Selection Phase')], max_length=30),
        ),
    ]
