# Generated by Django 6.0.1 on 2026-02-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_projecttask_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
