# Generated by Django 6.0.1 on 2026-02-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_lead_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='selected_services',
            field=models.JSONField(blank=True, help_text='Initial services selected during enquiry', null=True),
        ),
    ]
