# Generated by Django 6.0.1 on 2026-02-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='members',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
