# Generated by Django 6.0.1 on 2026-02-27 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_projectnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamResponseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_notifications', to='core.teammember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_responses', to='core.project')),
            ],
            options={
                'verbose_name': 'Team Response Notification',
                'verbose_name_plural': 'Team Response Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
