# Generated by Django 6.0.1 on 2026-03-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_teamresponsenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='selected_services',
            field=models.JSONField(default=list),
        ),
    ]
