# Generated by Django 6.0.1 on 2026-03-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_lead_selected_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='pricing_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
