# Generated by Django 6.0.1 on 2026-03-13 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_lead_pricing_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('TP', 'Traditional Photographer'), ('CP', 'Candid Photographer'), ('TV', 'Traditional Videographer'), ('CV', 'Candid Videographer'), ('DR', 'Drone Operator'), ('CI', 'Cinematic Videographer'), ('PH', 'Photographer'), ('VG', 'Videographer')], max_length=10)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['role', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCrewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_slot', models.CharField(max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_auto', models.BooleanField(default=False)),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.crewmember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'crew_member')},
            },
        ),
    ]
